from __future__ import annotations

from .stage_runner import StageDefinition


UNIFIED_STAGE_DEFINITIONS = [
    StageDefinition(
        "probe",
        config_keys=(
            "pipeline_strict",
            "video_output_format",
            "audio_output_format",
            "input_path",
            "input_size_bytes",
            "input_mtime_ns",
        ),
    ),
    StageDefinition(
        "asr",
        dependencies=("probe",),
        config_keys=(
            "pipeline_strict",
            "asr_model",
            "asr_device",
            "asr_compute_type",
            "asr_language",
            "asr_vad_filter",
        ),
    ),
    StageDefinition(
        "shot_detection",
        dependencies=("probe",),
        config_keys=(
            "pipeline_strict",
            "shot_detector_threshold",
            "motion_sample_fps",
        ),
    ),
    StageDefinition(
        "segmentation",
        dependencies=("asr", "shot_detection"),
        config_keys=(
            "segmentation_strategy",
            "fixed_segment_seconds",
            "segment_target_seconds",
            "segment_min_seconds",
            "segment_max_seconds",
            "segment_context_seconds",
            "pipeline_strict",
        ),
    ),
    StageDefinition(
        "tracking_base",
        dependencies=("segmentation",),
        config_keys=(
            "entity_tracking_model",
            "entity_tracking_tracker",
            "entity_tracking_fps",
            "entity_tracking_conf",
            "entity_tracking_iou",
            "entity_tracking_imgsz",
            "tracking_chunk_seconds",
            "disable_visual_identity_linking",
            "entity_source",
            "pipeline_strict",
        ),
    ),
    StageDefinition(
        "frame_selection",
        dependencies=("segmentation", "tracking_base", "shot_detection"),
        config_keys=(
            "frame_min",
            "frame_max",
            "frame_duplicate_threshold",
            "frame_marginal_gain_threshold",
            "pipeline_strict",
        ),
    ),
    StageDefinition(
        "text_entities",
        dependencies=("asr", "segmentation"),
        config_keys=(
            "spacy_model",
            "text_alias_similarity_threshold",
            "text_memory_short_term_mentions",
            "text_memory_long_term_entities",
            "text_memory_recent_events",
            "text_memory_recency_seconds",
            "text_reference_resolution_threshold",
            "text_reference_margin",
            "disable_transcript_memory",
            "pipeline_strict",
        ),
    ),
    StageDefinition(
        "alignment_caption",
        dependencies=(
            "frame_selection",
            "tracking_base",
            "text_entities",
        ),
        config_keys=(
            "caption_model_path",
            "caption_max_tokens",
            "caption_max_slice_nums",
            "entity_memory_recent_events",
            "openclip_model",
            "openclip_pretrained",
            "correspondence_similarity_threshold",
            "correspondence_similarity_margin",
            "correspondence_embedding_batch_size",
            "correspondence_device",
            "disable_crossmodal_alignment",
            "entity_source",
            "caption_alias_similarity_threshold",
            "extraction_gleaning_rounds",
            "pipeline_strict",
        ),
        preserve_on_restart=("captions.json",),
    ),
    StageDefinition(
        "graph_build",
        dependencies=("alignment_caption",),
        config_keys=("unified_graph_namespace",),
    ),
    StageDefinition(
        "embedding_index",
        dependencies=("graph_build",),
        config_keys=(
            "pipeline_strict",
            "video_embedding_batch_num",
            "video_embedding_dim",
        ),
    ),
    StageDefinition(
        "validation",
        dependencies=("embedding_index",),
        config_keys=(
            "graph_provenance_required",
            "graph_allow_provisional_nodes",
        ),
    ),
]
